/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, version 2.
 */

/** @file archipelago.h Archipelago multiworld randomizer integration. */

#ifndef ARCHIPELAGO_H
#define ARCHIPELAGO_H

#include <string>
#include <functional>
#include <thread>
#include <mutex>
#include <atomic>
#include <vector>
#include <deque>
#include <map>
#include <set>

enum Colours : uint8_t;

#include "company_type.h"
#include "engine_type.h"
#include "vehicle_type.h"

/** Connection states for the Archipelago client. */
enum class APState : uint8_t {
	DISCONNECTED,
	CONNECTING,
	CONNECTED,
	AUTHENTICATING,
	AUTHENTICATED,
	AP_ERROR,
};

/** A single item received from Archipelago. */
struct APItem {
	int64_t     item_id   = 0;
	std::string item_name;       ///< Resolved from slot_data item_id_to_name map
	bool        is_replay = false; ///< True when the server is replaying a previously received item on reconnect
};

/** A single mission generated by the APWorld. */
/** Named entity assigned to a mission at session start (town or industry on actual map). */
struct APNamedEntity {
	int32_t  id          = -1;       ///< TownID or IndustryID; -1 = not assigned
	std::string name;                ///< Display name substituted into mission description
	uint64_t cumulative  = 0;        ///< Accumulated progress (updated monthly)
	uint8_t  cargo_slot  = 0xFF;     ///< Industry cargo slot index (0xFF = not used)
	uint8_t  tae         = 0xFF;     ///< TownAcceptanceEffect (0xFF = not used)
	uint32_t tile        = UINT32_MAX; ///< Map tile (TileIndex) for viewport scroll; UINT32_MAX = unknown
	uint8_t   cargo_type = 0xFF; ///< Cargo type for cargomonitor (0xFF = invalid/not set)
};

struct APMission {
	std::string location;       ///< e.g. "Mission_Easy_001"
	std::string description;    ///< Human-readable goal text
	std::string type;           ///< "transport","earn £","have","service","build", etc.
	std::string difficulty;     ///< "easy","medium","hard","extreme"
	std::string cargo;          ///< May be empty
	std::string unit;           ///< "units","£","£/month","vehicles","trains","aircraft","road vehicles","towns","stations","passengers","purchase"
	std::string vehicle_key;    ///< For "transport_by_vehicle": "train","road_vehicle","ship","aircraft"
	int64_t     amount = 0;
	int64_t     current_value = 0; ///< Live progress – updated by CheckMissions() each tick
	bool        completed = false;
	/* "maintain" missions: counts consecutive months ALL stations have held the required rating */
	int32_t     maintain_months_ok = 0;
	bool        maintain_first_month_pending = true; ///< Absorb first timer fire after reset (prevents partial-month credit)
	/* Named entity missions: town or industry on the actual map */
	APNamedEntity named_entity;
};

struct APShopLocation {
	std::string location;
	std::string name;
	int64_t     cost = 0;
};

/** Full configuration received from the AP server after authentication. */
struct APSlotData {
	std::string             game_version;
	int                     mission_count        = 0;
	std::string             starting_vehicle;
	std::vector<std::string> starting_vehicles;   ///< all starters (>1 for one_of_each)
	bool                    enable_traps         = true;
	int                     start_year           = 1950;

	/* World generation parameters */
	uint32_t                world_seed           = 0;
	uint8_t                 map_x                = 8;
	uint8_t                 map_y                = 8;
	uint8_t                 landscape            = 0;
	uint8_t                 land_generator       = 1;
	uint8_t                 terrain_type         = 1;  ///< 0=very flat..4=alpinist
	uint8_t                 quantity_sea_lakes   = 0;  ///< 0=very low..3=high
	uint8_t                 variety              = 0;  ///< 0=none..5=very high
	uint8_t                 tgen_smoothness      = 1;  ///< 0=very smooth..3=very rough
	uint8_t                 amount_of_rivers     = 2;  ///< 0=none..3=many
	uint8_t                 water_border_presets = 0;  ///< 0=random,1=manual,2=infinite water
	uint8_t                 town_name            = 0;  ///< 0..255 town-name style index
	uint8_t                 number_towns         = 2;  ///< 0=very low..3=high
	uint8_t                 industry_density     = 4;  ///< 0=fund only,1=minimal,2=very low,3=low,4=normal,5=high

	/* ── Difficulty / balance ───────────────────────────────────────── */
	bool                    starting_cash_bonus  = false; ///< false=off, true=grant one full starting-loan amount
	bool                    enable_shop         = true;
	int                     shop_tiers          = 5;

	/* ── NewGRF options ─────────────────────────────────────────────── */
	bool                    enable_iron_horse    = false;

	/* ── Infrastructure locks (v0.2.0+) ────────────────────────────── */
	bool                    lock_bridges         = false;
	bool                    lock_tunnels         = false;
	bool                    lock_canals          = false;
	bool                    lock_terraforming    = false;

	/* ── New apworld (v0.1.0+) ──────────────────────────────────────── */
	int                     starting_cargo_type  = 0;   ///< 0=any, 1=Passengers, 2=Mail, 3=Coal, 4=Oil, 5=Livestock, 6=Grain, 7=Wood, 8=IronOre, 9=Valuables (matches Python StartingCargoType; Goods/Steel excluded)

	/** Maps item_id -> item_name, sent in slot_data by APWorld. */
	std::map<int64_t, std::string> item_id_to_name;
	/** Maps location_name -> location_id, sent in slot_data by APWorld. */
	std::map<std::string, int64_t> location_name_to_id;
	/** Location IDs already checked for this slot, sent by AP server on connect. */
	std::set<int64_t> checked_locations;

	/** Vehicle item names that should be locked at session start.
	 *  Only engines whose English name is in this set will be locked.
	 *  Engines NOT in this set (e.g. IH engines when enable_iron_horse=false)
	 *  are left available so the player can use them freely. */
	std::set<std::string> locked_vehicles;

	std::vector<APMission>  missions;
	std::vector<APShopLocation> shop_locations;
};

/** Message colour categories derived from AP PrintJSON parts. */
enum class APPrintColour : uint8_t {
	DEFAULT,
	RED,
	GREEN,
	YELLOW,
	BLUE,
	MAGENTA,
	CYAN,
	WHITE,
	ORANGE,
	PLUM,
	SLATEBLUE,
	SALMON,
};

/** Callbacks fired on the main thread via Tick(). */
struct APCallbacks {
	std::function<void()>                    on_connected;
	std::function<void(const std::string &)> on_disconnected;
	std::function<void(const APItem &)>      on_item_received;
	std::function<void(const std::string &, APPrintColour)> on_print;
	std::function<void(const APSlotData &)>  on_slot_data;
	/** Fired when RoomUpdate brings new checked_locations (e.g. from a co-client). */
	std::function<void()> on_locations_updated;
};

/** Archipelago WebSocket client. Networking runs in a background thread. */
class ArchipelagoClient {
public:
	ArchipelagoClient();
	~ArchipelagoClient();

	void Connect(const std::string &host, uint16_t port,
	             const std::string &slot, const std::string &password,
	             const std::string &game = "OpenTTD Cargolock",
	             bool use_ssl = false);
	void Disconnect();

	/** Send a location check by numeric ID. */
	void SendCheck(int64_t location_id);

	/** Send a location check by name (looks up ID from slot data). */
	void SendCheckByName(const std::string &location_name);

	/** Send victory / goal-complete status. */
	void SendGoal();

	/** Send a chat/command message to the AP server (e.g. "!hint item"). */
	void SendSay(const std::string &text);

	/** Returns the "player (game)" hint label for a location, or "" if not yet resolved. */
	std::string GetLocationHint(const std::string &location_name) const {
		auto id_it = location_ids.find(location_name);
		if (id_it == location_ids.end()) return "";
		auto hint_it = location_id_to_hint.find(id_it->second);
		if (hint_it == location_id_to_hint.end()) return "";
		return hint_it->second;
	}

	/** Dispatch queued callbacks on the main thread. Call every game tick. */
	void Tick();

	APState     GetState()     const { return state.load(); }
	std::string GetLastError() const { return last_error; }

	APSlotData GetSlotData() const {
		std::lock_guard<std::mutex> lg(slot_mutex);
		return slot_data;
	}
	bool HasSlotData() const { return has_slot_data.load(); }

	int64_t GetReceivedItemsIndex() const { return items_received_index.load(); }
	void    ResetReceivedItemsIndex()     { items_received_index.store(0); }
	void    SetReceivedItemsIndex(int64_t v) { items_received_index.store(v); }

	APCallbacks callbacks;

private:
	std::atomic<APState> state{ APState::DISCONNECTED };
	std::string last_error;

	std::string host, slot_name, password, game_name;
	uint16_t    port = 0;
	bool        ws_deflate{ false };   ///< true if server accepted permessage-deflate
	bool        use_ssl{ false };      ///< true → TLS/WSS via Schannel (Windows)

	mutable std::mutex slot_mutex;
	APSlotData         slot_data;
	std::atomic<bool>  has_slot_data{ false };

	/* Location name -> ID (filled from slot_data) */
	std::map<std::string, int64_t> location_ids;
	std::map<int64_t, std::string> location_id_to_name; ///< Reverse of location_ids
	std::map<int64_t, std::string> player_id_to_name;   ///< Slot number → player alias
	std::map<int64_t, std::string> player_id_to_game;   ///< Slot number → game name
	std::map<int64_t, std::string> location_id_to_hint; ///< location_id → "player (game)" label

	std::thread        worker_thread;
	std::atomic<bool>  stop_requested{ false };
	std::atomic<int64_t> items_received_index{ 0 }; ///< High-water mark of AP item indices processed; persists across reconnects

	struct InboundEvent {
		enum Type : uint8_t { CONNECTED, DISCONNECTED, ITEM, PRINT, SLOT_DATA, LOCATIONS_UPDATED } type;
		std::string text;
		APPrintColour colour = APPrintColour::DEFAULT;
		APItem      item;
		APSlotData  slot;
	};
	std::mutex               inbound_mutex;
	std::deque<InboundEvent> inbound_queue;

	struct OutboundMsg { std::string json; };
	std::mutex               outbound_mutex;
	std::deque<OutboundMsg>  outbound_queue;

	void        WorkerThread();
	bool        DoWebSocketHandshake(int sock, const std::string &h, uint16_t p);
	bool        SendWsText(int sock, const std::string &text);
	bool        RecvWsFrame(int sock, std::string &out_text, bool &out_closed);
	void        ProcessAPMessage(const std::string &json_text);
	void        PushEvent(InboundEvent ev);
	std::string PopOutbound();

#ifdef _WIN32
	void InitWinsock();
#endif
};

extern ArchipelagoClient *_ap_client;
void InitArchipelago();
void UninitArchipelago();

/**
 * Returns true when an Archipelago session is active (authenticated).
 * Called from engine.cpp to block the vanilla date-based vehicle introduction.
 */
bool AP_IsActive();

/** Returns true when the cargo type index is unlocked by AP items (client-local check). */
bool AP_IsCargoTypeUnlocked(uint8_t cargo_type);
bool AP_IsBridgesUnlocked();
bool AP_IsTunnelsUnlocked();
bool AP_IsCanalsUnlocked();
bool AP_IsTerraformingUnlocked();

/** Returns true when the cargo type is unlocked for a specific company (synchronized). */
bool AP_IsCompanyCargoUnlocked(CompanyID company, uint8_t cargo_type);
/** Reset per-company cargo unlock state (called at AP session start). */
void AP_ResetCompanyCargoUnlocks(CompanyID company);
void AP_RecordCargoDelivery(VehicleType vtype, CargoType ct, uint32_t amount);

/** Per-company AP-active flag — true if this company has AP restrictions (synchronized). */
bool AP_IsCompanyAPActive(CompanyID company);
/** Reset all per-company AP state (active flag, engine unlocks, airport tier). */
void AP_ResetCompanyAPState(CompanyID company);

/** Per-company engine unlock check (synchronized). Checks wagon cargo too. */
bool AP_IsCompanyEngineUnlocked(CompanyID company, EngineID eid);

/** Per-company airport type unlock check (synchronized via airport tier). */
bool AP_IsCompanyAirportTypeUnlocked(CompanyID company, uint8_t airport_type);

/** Get per-company airport tier count (synchronized). */
uint8_t AP_GetCompanyAirportTier(CompanyID company);

/** Returns true when at least one tier of the progressive item is unlocked. */
bool AP_IsTrainUnlocked();
bool AP_IsRoadVehicleUnlocked();
bool AP_IsAircraftUnlocked();
bool AP_IsShipUnlocked();

/** Returns true when an engine has been explicitly unlocked by AP items.
 *  Used by the build-vehicle GUI to filter the purchase list. */
bool AP_IsEngineUnlocked(EngineID eid);

/** Returns true when an airport type has been unlocked by AP progressive tiers.
 *  Used by the airport picker GUI to grey out locked airports. */
bool AP_IsAirportTypeUnlocked(uint8_t airport_type);

/** Returns true when a company colour is unlocked by AP items. */
bool AP_IsCompanyColourUnlocked(Colours colour);

/** Shop state accessors. */
int  AP_GetVisibleShopLocationCount();
bool AP_IsShopLocationPurchased(const std::string &location_name);
bool AP_PurchaseShopLocation(const std::string &location_name);
std::string AP_GetPurchasedShopLocationsStr();
void AP_SetPurchasedShopLocationsStr(const std::string &s);

/** Forward a text/command string to the AP server (Say packet). */
void AP_SendSay(const std::string &text);

/** Register the "ap" console command. Call once at startup. */
void AP_RegisterConsoleCommands();

/**
 * Called when the player exits a game (to menu, new game, load, etc.).
 * Disconnects from Archipelago and resets per-session state.
 */
void AP_OnLeaveGame();

/**
 * Set menu connect behavior:
 * true  = slot data from menu connection auto-starts a new AP world,
 * false = slot data from menu connection waits for player to load a save.
 */
void AP_SetMenuConnectStartNew(bool start_new);
void AP_SetMenuConnectMultiplayer(bool multiplayer_mode);

#endif /* ARCHIPELAGO_H */
